# Generated by Django 3.1.6 on 2021-03-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210318_1935'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schoolregistration',
            managers=[
            ],
        ),
    ]
