# Generated by Django 3.1.6 on 2021-03-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210318_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendencedata',
            old_name='school_left',
            new_name='school_left_unofficially',
        ),
    ]
