# Generated by Django 3.1.6 on 2021-03-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210318_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendencedata',
            name='school_left_unofficially',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
